### PR TITLE
Fix debug.py for InteractiveShellEmbed

### PR DESCRIPTION
**Pull request by minigraphx**
modified to new Module location

### CODE REVIEW

**Comment by icemac** [comment]
@minigraphx Thank you for this PR. Do you know what's the minimum version of IPython needed so this change works?

**Comment by minigraphx** [comment]
It's since 8.0.x (January 2022)

**Comment by icemac** [comment]
@minigraphx I intefgrated your change into #13 because I am not able to change this PR.

**Comment by icemac** [comment]
I just released https://pypi.org/project/grokcore.startup/4.1/ including this fix.

**Pull request closed without merging**
